test1: 
	@gcc -c JoaoFila.c
	@gcc -c JoaoLista.c
	@gcc -c ProgListaTarefas1.c
	@gcc -o prog *.o


test2: 
	@gcc -c JoaoFila.c
	@gcc -c JoaoLista.c
	@gcc -c ProgListaTarefas2.c
	@gcc -o prog *.o

test3: 
	@gcc -c JoaoFila.c
	@gcc -c JoaoLista.c
	@gcc -c ProgListaTarefas3.c
	@gcc -o prog *.o

clean:
	@rm -rf *.o && clear
